spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${DEMO_H2_PATH:${user.home}/.action-guard/demo-db/action_guard_demo};MODE=MySQL;AUTO_SERVER=TRUE
    username: ${DEMO_H2_USERNAME:sa}
    password: ${DEMO_H2_PASSWORD:}
  sql:
    init:
      mode: always
  rabbitmq:
    host: ${ACTION_GUARD_H2_RABBITMQ_HOST:localhost}
    port: ${ACTION_GUARD_H2_RABBITMQ_PORT:5672}
    username: ${ACTION_GUARD_H2_RABBITMQ_USERNAME:guest}
    password: ${ACTION_GUARD_H2_RABBITMQ_PASSWORD:guest}
    virtual-host: ${ACTION_GUARD_H2_RABBITMQ_VIRTUAL_HOST:/}
