spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:${ACTION_GUARD_H2_PATH:${user.home}/.action-guard/action-guard-db/action_guard};MODE=MySQL;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: action-guard-h2
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
